services:
  - type: web
    name: pathlet-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    branch: main
    buildCommand: docker build -t pathlet-api .
    startCommand: docker run -p 8000:8000 pathlet-api
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /healthz
    plan: free
