services:
  - type: web
    name: pathlet-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    branch: main
    buildCommand: docker build -t pathlet .
    startCommand: docker run -p 8000:8000 pathlet
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /healthz
    plan: free

  - type: web
    name: pathlet-frontend
    runtime: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://pathlet-api.onrender.com
    plan: free

  - type: worker
    name: pathlet-background-tasks
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python backend/background_tasks.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
