services:
  - type: web
    name: pathlet-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    branch: main
    buildCommand: docker build -t pathlet-api .
    startCommand: docker run -p 8000:8000 pathlet-api
    envVars:
      - key: FLASK_ENV
        value: production
    healthCheckPath: /healthz
    plan: free

  - type: web
    name: pathlet-web
    runtime: static
    buildCommand: |
      mkdir -p build
      cp frontend/index.html build/index.html
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free

  - type: worker
    name: pathlet-background-tasks
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python backend/background_tasks.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
