services:
  - type: web
    name: pathlet-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install .
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
      - key: FLASK_ENV
        value: production
      - key: HUGGING_FACE_API_KEY
        sync: false

  - type: web
    name: pathlet-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: worker
    name: pathlet-background-tasks
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python backend/background_tasks.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.19
